# Generated by Django 3.0.2 on 2024-04-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckdApp', '0002_auto_20200205_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Blood_Glucose_Random',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Blood_Urea',
            new_name='DailyRate',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Packed_cell_volume',
            new_name='MonthlyIncome',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Serum_Creatine',
            new_name='MonthlyRate',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='White_blood_count',
            new_name='TotalWorkingYears',
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='YearsAtCompany',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='YearsInCurrentRole',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='YearsWithCurrManager',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
